### PR TITLE
Updated pom.xml with testng libraries

### PR DESCRIPTION
**Pull request by Rutujakalyane**
Hi,
 I have Updated pom.xml with testng library. kindly have a look at once. 
Regards,
 Rutuja

### CODE REVIEW

**Review by VasantChavan — COMMENTED** [review]
Hi Rutuja,

Kindly add selenium, POI and extent report libraries into pom.xml file.


Regards,
Vasant

**Comment by Rutujakalyane** [comment]
Hi,
Added selenium,POI and extent report libraries.
Regards,
Rutuja.

**Comment by VasantChavan** [comment]
Hi Rutuja, 


It looks fine pom.xml libraries  now, You can merge with master.

Regards,
Vasant

**Comment by Rutujakalyane** [comment]
Thank you, I will merge my branch with master.

**Pull request merged**
